repos:
  - repo: local
    hooks:
      - id: compile23
        name: Compile python files using the expected runtime version
        entry: ./tools/compile23.py
        language: script

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-logging-format
          - flake8-implicit-str-concat
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    - id: check-xml
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-symlinks
    - id: debug-statements
